default:
  resource:
    - from_path: "./stock.db"
      to_path: "/data/stock.db"
    - from_path: "./portfolio.db"
      to_path: "/data/portfolio.db"
  content:
    - name: "Stock Portfolio Report"
      path: "./report-portfolio"
      description: "This parameterized rmarkdown report illustrates scheduled, customized emails and user-editable parameterization of reporting"
      tag:
        - "Demo Content|Stock Portfolio"
      url: "/stock-portfolio/report/"
      send_email: true
      image: "img/stock-portfolio-report.png"
    - name: "Stock Portfolio PowerPoint and PDF"
      path: "./report-portfolio-ppt-pdf"
      description: "This parameterized rmarkdown report illustrates customized emails, PDF output, and a PowerPoint Presentation attached to outgoing emails"
      tag:
        - "Demo Content|Stock Portfolio"
      url: "/stock-portfolio/report-ppt-pdf/"
      send_email: true
    - name: "Stock Portfolio Shiny Document"
      path: "./shiny-app"
      description: "This Shiny Application + R Markdown document allows interactive exploration of portfolio returns along with tuning of model parameters"
      tag: "Demo Content|Stock Portfolio"
      url: "/stock-portfolio/app/"
      image: "img/stock-portfolio-app.png"
    - name: "Stock Information Plumber API"
      path: "./api"
      description: "This Plumber API surfaces the ability to programmatically request price history or a number representing the relative volatility of a stock ticker"
      tag: "Demo Content|Stock Portfolio"
      url: "/stock-portfolio/api/"
      image: "img/stock-portfolio-api.png"
